name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEPNOTE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        use-public-rspm: true

    - name: Set up pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libxml2-dev libssl-dev

    - name: Install dependencies
      run: |
        R -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv', repos = 'https://cloud.r-project.org')"
        R -e "renv::restore(lockfile = 'renv.lock')"
        R -e "if (!requireNamespace('devtools', quietly = TRUE)) install.packages('devtools', repos = 'https://cloud.r-project.org')"
        R -e "devtools::install_deps(dependencies = TRUE)"
        R -e "install.packages(c('rcmdcheck', 'covr'), repos = 'https://cloud.r-project.org')"

    - name: Check package
      run: |
        R -e "devtools::check(error_on = 'error', args = c('--no-manual', '--as-cran'))"

    - name: Upload check results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-check-results
        path: |
          check/*.Rcheck
          check/*.log
          check/*.out

    - name: Test coverage
      if: runner.os == 'Linux' && matrix.config.r == 'release'
      run: |
        R -e "covr::codecov()"
      continue-on-error: true